// src/main/webapp/app/entities/hospital/hospital.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('sahatiApp.hospital.home.title')" id="hospital-heading">Hospitals</span>
            <router-link :to="{name: 'HospitalCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-hospital">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('sahatiApp.hospital.home.createLabel')">
                    Create a new Hospital
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && hospitals && hospitals.length === 0">
            <span v-text="$t('sahatiApp.hospital.home.notFound')">No hospitals found</span>
        </div>
        <div class="table-responsive" v-if="hospitals && hospitals.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('nameAr')"><span v-text="$t('sahatiApp.hospital.nameAr')">Name Ar</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'nameAr'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('nameEn')"><span v-text="$t('sahatiApp.hospital.nameEn')">Name En</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'nameEn'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('email')"><span v-text="$t('sahatiApp.hospital.email')">Email</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'email'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('phone')"><span v-text="$t('sahatiApp.hospital.phone')">Phone</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'phone'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('address')"><span v-text="$t('sahatiApp.hospital.address')">Address</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'address'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="hospital in hospitals"
                    :key="hospital.id">
                    <td>
                        <router-link :to="{name: 'HospitalView', params: {hospitalId: hospital.id}}">{{hospital.id}}</router-link>
                    </td>
                    <td>{{hospital.nameAr}}</td>
                    <td>{{hospital.nameEn}}</td>
                    <td>{{hospital.email}}</td>
                    <td>{{hospital.phone}}</td>
                    <td>{{hospital.address}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'HospitalView', params: {hospitalId: hospital.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'HospitalEdit', params: {hospitalId: hospital.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(hospital)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="sahatiApp.hospital.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-hospital-heading" v-text="$t('sahatiApp.hospital.delete.question', {'id': removeId})">Are you sure you want to delete this Hospital?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-hospital" v-text="$t('entity.action.delete')" v-on:click="removeHospital()">Delete</button>
            </div>
        </b-modal>
        <div v-show="hospitals && hospitals.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./hospital.component.ts">
</script>

// src/main/webapp/app/entities/hospital/hospital.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IHospital } from 'app/shared/model/hospital.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { HospitalService } from './hospital.service';
import { HospitalDeleteDialogComponent } from './hospital-delete-dialog.component';

@Component({
  selector: 'jhi-hospital',
  templateUrl: './hospital.component.html'
})
export class HospitalComponent implements OnInit, OnDestroy {
  hospitals?: IHospital[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected hospitalService: HospitalService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number): void {
    const pageToLoad: number = page || this.page;

    this.hospitalService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IHospital[]>) => this.onSuccess(res.body, res.headers, pageToLoad),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.ascending = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
      this.ngbPaginationPage = data.pagingParams.page;
      this.loadPage();
    });
    this.registerChangeInHospitals();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IHospital): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInHospitals(): void {
    this.eventSubscriber = this.eventManager.subscribe('hospitalListModification', () => this.loadPage());
  }

  delete(hospital: IHospital): void {
    const modalRef = this.modalService.open(HospitalDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.hospital = hospital;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IHospital[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.router.navigate(['/hospital'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc')
      }
    });
    this.hospitals = data || [];
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="sahatiApp.hospital.home.title">Hospitals</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-hospital" [routerLink]="['/hospital/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="sahatiApp.hospital.home.createLabel">
            Create a new Hospital
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="hospitals?.length === 0">
        <span jhiTranslate="sahatiApp.hospital.home.notFound">No hospitals found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="hospitals?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nameAr"><span jhiTranslate="sahatiApp.hospital.nameAr">Name Ar</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nameEn"><span jhiTranslate="sahatiApp.hospital.nameEn">Name En</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="email"><span jhiTranslate="sahatiApp.hospital.email">Email</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="phone"><span jhiTranslate="sahatiApp.hospital.phone">Phone</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="address"><span jhiTranslate="sahatiApp.hospital.address">Address</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let hospital of hospitals ;trackBy: trackId">
                    <td><a [routerLink]="['/hospital', hospital.id, 'view']">{{ hospital.id }}</a></td>
                    <td>{{ hospital.nameAr }}</td>
                    <td>{{ hospital.nameEn }}</td>
                    <td>{{ hospital.email }}</td>
                    <td>{{ hospital.phone }}</td>
                    <td>{{ hospital.address }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/hospital', hospital.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/hospital', hospital.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(hospital)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="hospitals?.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
