// src/main/webapp/app/entities/invoice-benefits/invoice-benefits-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="sahatiApp.invoiceBenefits.home.createOrEditLabel" v-text="$t('sahatiApp.invoiceBenefits.home.createOrEditLabel')">Create or edit a InvoiceBenefits</h2>
                <div>
                    <div class="form-group" v-if="invoiceBenefits.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="invoiceBenefits.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.pointsCost')" for="invoice-benefits-pointsCost">Points Cost</label>
                        <input type="number" class="form-control" name="pointsCost" id="invoice-benefits-pointsCost"
                            :class="{'valid': !$v.invoiceBenefits.pointsCost.$invalid, 'invalid': $v.invoiceBenefits.pointsCost.$invalid }" v-model.number="$v.invoiceBenefits.pointsCost.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.cost')" for="invoice-benefits-cost">Cost</label>
                        <input type="number" class="form-control" name="cost" id="invoice-benefits-cost"
                            :class="{'valid': !$v.invoiceBenefits.cost.$invalid, 'invalid': $v.invoiceBenefits.cost.$invalid }" v-model.number="$v.invoiceBenefits.cost.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.quantity')" for="invoice-benefits-quantity">Quantity</label>
                        <input type="number" class="form-control" name="quantity" id="invoice-benefits-quantity"
                            :class="{'valid': !$v.invoiceBenefits.quantity.$invalid, 'invalid': $v.invoiceBenefits.quantity.$invalid }" v-model.number="$v.invoiceBenefits.quantity.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.total')" for="invoice-benefits-total">Total</label>
                        <input type="number" class="form-control" name="total" id="invoice-benefits-total"
                            :class="{'valid': !$v.invoiceBenefits.total.$invalid, 'invalid': $v.invoiceBenefits.total.$invalid }" v-model.number="$v.invoiceBenefits.total.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.benefit')" for="invoice-benefits-benefit">Benefit</label>
                        <select class="form-control" id="invoice-benefits-benefit" name="benefit" v-model="invoiceBenefits.benefitId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="benefitOption.id" v-for="benefitOption in benefits" :key="benefitOption.id">{{benefitOption.nameAr}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.invoiceBenefits.invoice')" for="invoice-benefits-invoice">Invoice</label>
                        <select class="form-control" id="invoice-benefits-invoice" name="invoice" v-model="invoiceBenefits.invoiceId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="invoiceOption.id" v-for="invoiceOption in invoices" :key="invoiceOption.id">{{invoiceOption.invoiceNo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.invoiceBenefits.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./invoice-benefits-update.component.ts">
</script>

// src/main/webapp/app/entities/invoice-benefits/invoice-benefits-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IInvoiceBenefits, InvoiceBenefits } from 'app/shared/model/invoice-benefits.model';
import { InvoiceBenefitsService } from './invoice-benefits.service';
import { IBenefit } from 'app/shared/model/benefit.model';
import { BenefitService } from 'app/entities/benefit/benefit.service';
import { IInvoice } from 'app/shared/model/invoice.model';
import { InvoiceService } from 'app/entities/invoice/invoice.service';

type SelectableEntity = IBenefit | IInvoice;

@Component({
  selector: 'jhi-invoice-benefits-update',
  templateUrl: './invoice-benefits-update.component.html'
})
export class InvoiceBenefitsUpdateComponent implements OnInit {
  isSaving = false;
  benefits: IBenefit[] = [];
  invoices: IInvoice[] = [];

  editForm = this.fb.group({
    id: [],
    pointsCost: [],
    cost: [],
    quantity: [],
    total: [],
    benefitId: [],
    invoiceId: []
  });

  constructor(
    protected invoiceBenefitsService: InvoiceBenefitsService,
    protected benefitService: BenefitService,
    protected invoiceService: InvoiceService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ invoiceBenefits }) => {
      this.updateForm(invoiceBenefits);

      this.benefitService.query().subscribe((res: HttpResponse<IBenefit[]>) => (this.benefits = res.body || []));

      this.invoiceService.query().subscribe((res: HttpResponse<IInvoice[]>) => (this.invoices = res.body || []));
    });
  }

  updateForm(invoiceBenefits: IInvoiceBenefits): void {
    this.editForm.patchValue({
      id: invoiceBenefits.id,
      pointsCost: invoiceBenefits.pointsCost,
      cost: invoiceBenefits.cost,
      quantity: invoiceBenefits.quantity,
      total: invoiceBenefits.total,
      benefitId: invoiceBenefits.benefitId,
      invoiceId: invoiceBenefits.invoiceId
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const invoiceBenefits = this.createFromForm();
    if (invoiceBenefits.id !== undefined) {
      this.subscribeToSaveResponse(this.invoiceBenefitsService.update(invoiceBenefits));
    } else {
      this.subscribeToSaveResponse(this.invoiceBenefitsService.create(invoiceBenefits));
    }
  }

  private createFromForm(): IInvoiceBenefits {
    return {
      ...new InvoiceBenefits(),
      id: this.editForm.get(['id'])!.value,
      pointsCost: this.editForm.get(['pointsCost'])!.value,
      cost: this.editForm.get(['cost'])!.value,
      quantity: this.editForm.get(['quantity'])!.value,
      total: this.editForm.get(['total'])!.value,
      benefitId: this.editForm.get(['benefitId'])!.value,
      invoiceId: this.editForm.get(['invoiceId'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IInvoiceBenefits>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-invoice-benefits-heading" jhiTranslate="sahatiApp.invoiceBenefits.home.createOrEditLabel">Create or edit a Invoice Benefits</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.pointsCost" for="field_pointsCost">Points Cost</label>
                    <input type="number" class="form-control" name="pointsCost" id="field_pointsCost"
                           formControlName="pointsCost"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.cost" for="field_cost">Cost</label>
                    <input type="number" class="form-control" name="cost" id="field_cost"
                           formControlName="cost"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.quantity" for="field_quantity">Quantity</label>
                    <input type="number" class="form-control" name="quantity" id="field_quantity"
                           formControlName="quantity"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.total" for="field_total">Total</label>
                    <input type="number" class="form-control" name="total" id="field_total"
                           formControlName="total"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.benefit" for="field_benefit">Benefit</label>
                    <select class="form-control" id="field_benefit" name="benefit" formControlName="benefitId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="benefitOption.id" *ngFor="let benefitOption of benefits; trackBy: trackById">{{ benefitOption.nameAr }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.invoiceBenefits.invoice" for="field_invoice">Invoice</label>
                    <select class="form-control" id="field_invoice" name="invoice" formControlName="invoiceId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="invoiceOption.id" *ngFor="let invoiceOption of invoices; trackBy: trackById">{{ invoiceOption.invoiceNo }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
