// src/main/webapp/app/entities/invoice-benefits/invoice-benefits.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IInvoiceBenefits } from 'app/shared/model/invoice-benefits.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { InvoiceBenefitsService } from './invoice-benefits.service';
import { InvoiceBenefitsDeleteDialogComponent } from './invoice-benefits-delete-dialog.component';

@Component({
  selector: 'jhi-invoice-benefits',
  templateUrl: './invoice-benefits.component.html'
})
export class InvoiceBenefitsComponent implements OnInit, OnDestroy {
  invoiceBenefits?: IInvoiceBenefits[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected invoiceBenefitsService: InvoiceBenefitsService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number): void {
    const pageToLoad: number = page || this.page;

    this.invoiceBenefitsService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IInvoiceBenefits[]>) => this.onSuccess(res.body, res.headers, pageToLoad),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.ascending = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
      this.ngbPaginationPage = data.pagingParams.page;
      this.loadPage();
    });
    this.registerChangeInInvoiceBenefits();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IInvoiceBenefits): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInInvoiceBenefits(): void {
    this.eventSubscriber = this.eventManager.subscribe('invoiceBenefitsListModification', () => this.loadPage());
  }

  delete(invoiceBenefits: IInvoiceBenefits): void {
    const modalRef = this.modalService.open(InvoiceBenefitsDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.invoiceBenefits = invoiceBenefits;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IInvoiceBenefits[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.router.navigate(['/invoice-benefits'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc')
      }
    });
    this.invoiceBenefits = data || [];
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="sahatiApp.invoiceBenefits.home.title">Invoice Benefits</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-invoice-benefits" [routerLink]="['/invoice-benefits/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="sahatiApp.invoiceBenefits.home.createLabel">
            Create a new Invoice Benefits
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="invoiceBenefits?.length === 0">
        <span jhiTranslate="sahatiApp.invoiceBenefits.home.notFound">No invoiceBenefits found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="invoiceBenefits?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="pointsCost"><span jhiTranslate="sahatiApp.invoiceBenefits.pointsCost">Points Cost</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="cost"><span jhiTranslate="sahatiApp.invoiceBenefits.cost">Cost</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="quantity"><span jhiTranslate="sahatiApp.invoiceBenefits.quantity">Quantity</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="total"><span jhiTranslate="sahatiApp.invoiceBenefits.total">Total</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="benefitNameAr"><span jhiTranslate="sahatiApp.invoiceBenefits.benefit">Benefit</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="invoiceInvoiceNo"><span jhiTranslate="sahatiApp.invoiceBenefits.invoice">Invoice</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let invoiceBenefits of invoiceBenefits ;trackBy: trackId">
                    <td><a [routerLink]="['/invoice-benefits', invoiceBenefits.id, 'view']">{{ invoiceBenefits.id }}</a></td>
                    <td>{{ invoiceBenefits.pointsCost }}</td>
                    <td>{{ invoiceBenefits.cost }}</td>
                    <td>{{ invoiceBenefits.quantity }}</td>
                    <td>{{ invoiceBenefits.total }}</td>
                    <td>
                        <div *ngIf="invoiceBenefits.benefitId">
                            <a [routerLink]="['/benefit', invoiceBenefits.benefitId , 'view']" >{{ invoiceBenefits.benefitNameAr }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="invoiceBenefits.invoiceId">
                            <a [routerLink]="['/invoice', invoiceBenefits.invoiceId , 'view']" >{{ invoiceBenefits.invoiceInvoiceNo }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/invoice-benefits', invoiceBenefits.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/invoice-benefits', invoiceBenefits.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(invoiceBenefits)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="invoiceBenefits?.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/invoice-benefits/invoice-benefits.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('sahatiApp.invoiceBenefits.home.title')" id="invoice-benefits-heading">Invoice Benefits</span>
            <router-link :to="{name: 'InvoiceBenefitsCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-invoice-benefits">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('sahatiApp.invoiceBenefits.home.createLabel')">
                    Create a new Invoice Benefits
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && invoiceBenefits && invoiceBenefits.length === 0">
            <span v-text="$t('sahatiApp.invoiceBenefits.home.notFound')">No invoiceBenefits found</span>
        </div>
        <div class="table-responsive" v-if="invoiceBenefits && invoiceBenefits.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('pointsCost')"><span v-text="$t('sahatiApp.invoiceBenefits.pointsCost')">Points Cost</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'pointsCost'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('cost')"><span v-text="$t('sahatiApp.invoiceBenefits.cost')">Cost</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'cost'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('quantity')"><span v-text="$t('sahatiApp.invoiceBenefits.quantity')">Quantity</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'quantity'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('total')"><span v-text="$t('sahatiApp.invoiceBenefits.total')">Total</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'total'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('benefitNameAr')"><span v-text="$t('sahatiApp.invoiceBenefits.benefit')">Benefit</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'benefitNameAr'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('invoiceInvoiceNo')"><span v-text="$t('sahatiApp.invoiceBenefits.invoice')">Invoice</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'invoiceInvoiceNo'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="invoiceBenefits in invoiceBenefits"
                    :key="invoiceBenefits.id">
                    <td>
                        <router-link :to="{name: 'InvoiceBenefitsView', params: {invoiceBenefitsId: invoiceBenefits.id}}">{{invoiceBenefits.id}}</router-link>
                    </td>
                    <td>{{invoiceBenefits.pointsCost}}</td>
                    <td>{{invoiceBenefits.cost}}</td>
                    <td>{{invoiceBenefits.quantity}}</td>
                    <td>{{invoiceBenefits.total}}</td>
                    <td>
                        <div v-if="invoiceBenefits.benefitId">
                            <router-link :to="{name: 'BenefitView', params: {benefitId: invoiceBenefits.benefitId}}">{{invoiceBenefits.benefitNameAr}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="invoiceBenefits.invoiceId">
                            <router-link :to="{name: 'InvoiceView', params: {invoiceId: invoiceBenefits.invoiceId}}">{{invoiceBenefits.invoiceInvoiceNo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'InvoiceBenefitsView', params: {invoiceBenefitsId: invoiceBenefits.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'InvoiceBenefitsEdit', params: {invoiceBenefitsId: invoiceBenefits.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(invoiceBenefits)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="sahatiApp.invoiceBenefits.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-invoiceBenefits-heading" v-text="$t('sahatiApp.invoiceBenefits.delete.question', {'id': removeId})">Are you sure you want to delete this Invoice Benefits?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-invoiceBenefits" v-text="$t('entity.action.delete')" v-on:click="removeInvoiceBenefits()">Delete</button>
            </div>
        </b-modal>
        <div v-show="invoiceBenefits && invoiceBenefits.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./invoice-benefits.component.ts">
</script>
