// src/main/webapp/app/entities/attatchment/attatchment-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="sahatiApp.attatchment.home.createOrEditLabel" v-text="$t('sahatiApp.attatchment.home.createOrEditLabel')">Create or edit a Attatchment</h2>
                <div>
                    <div class="form-group" v-if="attatchment.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="attatchment.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.attatchment.name')" for="attatchment-name">Name</label>
                        <input type="text" class="form-control" name="name" id="attatchment-name"
                            :class="{'valid': !$v.attatchment.name.$invalid, 'invalid': $v.attatchment.name.$invalid }" v-model="$v.attatchment.name.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.attatchment.file')" for="attatchment-file">File</label>
                        <div>
                            <div v-if="attatchment.file" class="form-text text-danger clearfix">
                                <a class="pull-left" v-on:click="openFile(attatchment.fileContentType, attatchment.file)" v-text="$t('entity.action.open')">open</a><br>
                                <span class="pull-left">{{attatchment.fileContentType}}, {{byteSize(attatchment.file)}}</span>
                                <button type="button" v-on:click="attatchment.file=null;attatchment.fileContentType=null;"
                                        class="btn btn-secondary btn-xs pull-right">
                                    <font-awesome-icon icon="times"></font-awesome-icon>
                                </button>
                            </div>
                            <input type="file" ref="file_file" id="file_file" v-on:change="setFileData($event, attatchment, 'file', false)" v-text="$t('entity.action.addblob')"/>
                        </div>
                        <input type="hidden" class="form-control" name="file" id="attatchment-file"
                            :class="{'valid': !$v.attatchment.file.$invalid, 'invalid': $v.attatchment.file.$invalid }" v-model="$v.attatchment.file.$model" />
                        <input type="hidden" class="form-control" name="fileContentType" id="attatchment-fileContentType"
                            v-model="attatchment.fileContentType" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.attatchment.fileUrl')" for="attatchment-fileUrl">File Url</label>
                        <input type="text" class="form-control" name="fileUrl" id="attatchment-fileUrl"
                            :class="{'valid': !$v.attatchment.fileUrl.$invalid, 'invalid': $v.attatchment.fileUrl.$invalid }" v-model="$v.attatchment.fileUrl.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.attatchment.employee')" for="attatchment-employee">Employee</label>
                        <select class="form-control" id="attatchment-employee" name="employee" v-model="attatchment.employeeId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="employeeOption.id" v-for="employeeOption in employees" :key="employeeOption.id">{{employeeOption.name}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.attatchment.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./attatchment-update.component.ts">
</script>

// src/main/webapp/app/entities/attatchment/attatchment-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IAttatchment, Attatchment } from 'app/shared/model/attatchment.model';
import { AttatchmentService } from './attatchment.service';
import { AlertError } from 'app/shared/alert/alert-error.model';
import { IEmployee } from 'app/shared/model/employee.model';
import { EmployeeService } from 'app/entities/employee/employee.service';

@Component({
  selector: 'jhi-attatchment-update',
  templateUrl: './attatchment-update.component.html'
})
export class AttatchmentUpdateComponent implements OnInit {
  isSaving = false;
  employees: IEmployee[] = [];

  editForm = this.fb.group({
    id: [],
    name: [],
    file: [],
    fileContentType: [],
    fileUrl: [],
    employeeId: []
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected attatchmentService: AttatchmentService,
    protected employeeService: EmployeeService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ attatchment }) => {
      this.updateForm(attatchment);

      this.employeeService.query().subscribe((res: HttpResponse<IEmployee[]>) => (this.employees = res.body || []));
    });
  }

  updateForm(attatchment: IAttatchment): void {
    this.editForm.patchValue({
      id: attatchment.id,
      name: attatchment.name,
      file: attatchment.file,
      fileContentType: attatchment.fileContentType,
      fileUrl: attatchment.fileUrl,
      employeeId: attatchment.employeeId
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: Event, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('sahatiApp.error', { ...err, key: 'error.file.' + err.key })
      );
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const attatchment = this.createFromForm();
    if (attatchment.id !== undefined) {
      this.subscribeToSaveResponse(this.attatchmentService.update(attatchment));
    } else {
      this.subscribeToSaveResponse(this.attatchmentService.create(attatchment));
    }
  }

  private createFromForm(): IAttatchment {
    return {
      ...new Attatchment(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      fileContentType: this.editForm.get(['fileContentType'])!.value,
      file: this.editForm.get(['file'])!.value,
      fileUrl: this.editForm.get(['fileUrl'])!.value,
      employeeId: this.editForm.get(['employeeId'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAttatchment>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: IEmployee): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-attatchment-heading" jhiTranslate="sahatiApp.attatchment.home.createOrEditLabel">Create or edit a Attatchment</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.attatchment.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.attatchment.file" for="field_file">File</label>
                    <div>
                        <div *ngIf="editForm.get('file')!.value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('fileContentType')!.value, editForm.get('file')!.value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{ editForm.get('fileContentType')!.value }}, {{ byteSize(editForm.get('file')!.value) }}</span>
                            <button type="button" (click)="editForm.patchValue({file: null});editForm.patchValue({fileContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon icon="times"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_file" (change)="setFileData($event, 'file', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="file" id="field_file"
                           formControlName="file"/>
                    <input type="hidden" class="form-control" name="fileContentType" id="field_fileContentType"
                           formControlName="fileContentType" />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.attatchment.fileUrl" for="field_fileUrl">File Url</label>
                    <input type="text" class="form-control" name="fileUrl" id="field_fileUrl"
                           formControlName="fileUrl"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.attatchment.employee" for="field_employee">Employee</label>
                    <select class="form-control" id="field_employee" name="employee" formControlName="employeeId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="employeeOption.id" *ngFor="let employeeOption of employees; trackBy: trackById">{{ employeeOption.name }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
