// src/main/webapp/app/entities/attatchment/attatchment.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('sahatiApp.attatchment.home.title')" id="attatchment-heading">Attatchments</span>
            <router-link :to="{name: 'AttatchmentCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-attatchment">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('sahatiApp.attatchment.home.createLabel')">
                    Create a new Attatchment
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && attatchments && attatchments.length === 0">
            <span v-text="$t('sahatiApp.attatchment.home.notFound')">No attatchments found</span>
        </div>
        <div class="table-responsive" v-if="attatchments && attatchments.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('name')"><span v-text="$t('sahatiApp.attatchment.name')">Name</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'name'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('file')"><span v-text="$t('sahatiApp.attatchment.file')">File</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'file'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('fileUrl')"><span v-text="$t('sahatiApp.attatchment.fileUrl')">File Url</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'fileUrl'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('employeeName')"><span v-text="$t('sahatiApp.attatchment.employee')">Employee</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'employeeName'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="attatchment in attatchments"
                    :key="attatchment.id">
                    <td>
                        <router-link :to="{name: 'AttatchmentView', params: {attatchmentId: attatchment.id}}">{{attatchment.id}}</router-link>
                    </td>
                    <td>{{attatchment.name}}</td>
                    <td>
                        <a v-if="attatchment.file" v-on:click="openFile(attatchment.fileContentType, attatchment.file)" v-text="$t('entity.action.open')">open</a>
                        <span v-if="attatchment.file">{{attatchment.fileContentType}}, {{byteSize(attatchment.file)}}</span>
                    </td>
                    <td>{{attatchment.fileUrl}}</td>
                    <td>
                        <div v-if="attatchment.employeeId">
                            <router-link :to="{name: 'EmployeeView', params: {employeeId: attatchment.employeeId}}">{{attatchment.employeeName}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'AttatchmentView', params: {attatchmentId: attatchment.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'AttatchmentEdit', params: {attatchmentId: attatchment.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(attatchment)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="sahatiApp.attatchment.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-attatchment-heading" v-text="$t('sahatiApp.attatchment.delete.question', {'id': removeId})">Are you sure you want to delete this Attatchment?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-attatchment" v-text="$t('entity.action.delete')" v-on:click="removeAttatchment()">Delete</button>
            </div>
        </b-modal>
        <div v-show="attatchments && attatchments.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./attatchment.component.ts">
</script>

// src/main/webapp/app/entities/attatchment/attatchment.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiDataUtils } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAttatchment } from 'app/shared/model/attatchment.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { AttatchmentService } from './attatchment.service';
import { AttatchmentDeleteDialogComponent } from './attatchment-delete-dialog.component';

@Component({
  selector: 'jhi-attatchment',
  templateUrl: './attatchment.component.html'
})
export class AttatchmentComponent implements OnInit, OnDestroy {
  attatchments?: IAttatchment[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected attatchmentService: AttatchmentService,
    protected activatedRoute: ActivatedRoute,
    protected dataUtils: JhiDataUtils,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number): void {
    const pageToLoad: number = page || this.page;

    this.attatchmentService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IAttatchment[]>) => this.onSuccess(res.body, res.headers, pageToLoad),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.ascending = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
      this.ngbPaginationPage = data.pagingParams.page;
      this.loadPage();
    });
    this.registerChangeInAttatchments();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IAttatchment): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    return this.dataUtils.openFile(contentType, base64String);
  }

  registerChangeInAttatchments(): void {
    this.eventSubscriber = this.eventManager.subscribe('attatchmentListModification', () => this.loadPage());
  }

  delete(attatchment: IAttatchment): void {
    const modalRef = this.modalService.open(AttatchmentDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.attatchment = attatchment;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IAttatchment[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.router.navigate(['/attatchment'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc')
      }
    });
    this.attatchments = data || [];
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="sahatiApp.attatchment.home.title">Attatchments</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-attatchment" [routerLink]="['/attatchment/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="sahatiApp.attatchment.home.createLabel">
            Create a new Attatchment
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="attatchments?.length === 0">
        <span jhiTranslate="sahatiApp.attatchment.home.notFound">No attatchments found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="attatchments?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="name"><span jhiTranslate="sahatiApp.attatchment.name">Name</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="file"><span jhiTranslate="sahatiApp.attatchment.file">File</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="fileUrl"><span jhiTranslate="sahatiApp.attatchment.fileUrl">File Url</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="employeeName"><span jhiTranslate="sahatiApp.attatchment.employee">Employee</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let attatchment of attatchments ;trackBy: trackId">
                    <td><a [routerLink]="['/attatchment', attatchment.id, 'view']">{{ attatchment.id }}</a></td>
                    <td>{{ attatchment.name }}</td>
                    <td>
                        <a *ngIf="attatchment.file" (click)="openFile(attatchment.fileContentType, attatchment.file)" jhiTranslate="entity.action.open">open</a>
                        <span *ngIf="attatchment.file">{{ attatchment.fileContentType }}, {{ byteSize(attatchment.file) }}</span>
                    </td>
                    <td>{{ attatchment.fileUrl }}</td>
                    <td>
                        <div *ngIf="attatchment.employeeId">
                            <a [routerLink]="['/employee', attatchment.employeeId , 'view']" >{{ attatchment.employeeName }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/attatchment', attatchment.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/attatchment', attatchment.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(attatchment)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="attatchments?.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
