// src/main/webapp/app/entities/benefit-request/benefit-request.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBenefitRequest } from 'app/shared/model/benefit-request.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { BenefitRequestService } from './benefit-request.service';
import { BenefitRequestDeleteDialogComponent } from './benefit-request-delete-dialog.component';

@Component({
  selector: 'jhi-benefit-request',
  templateUrl: './benefit-request.component.html'
})
export class BenefitRequestComponent implements OnInit, OnDestroy {
  benefitRequests?: IBenefitRequest[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected benefitRequestService: BenefitRequestService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number): void {
    const pageToLoad: number = page || this.page;

    this.benefitRequestService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IBenefitRequest[]>) => this.onSuccess(res.body, res.headers, pageToLoad),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.ascending = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
      this.ngbPaginationPage = data.pagingParams.page;
      this.loadPage();
    });
    this.registerChangeInBenefitRequests();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IBenefitRequest): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInBenefitRequests(): void {
    this.eventSubscriber = this.eventManager.subscribe('benefitRequestListModification', () => this.loadPage());
  }

  delete(benefitRequest: IBenefitRequest): void {
    const modalRef = this.modalService.open(BenefitRequestDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.benefitRequest = benefitRequest;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IBenefitRequest[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.router.navigate(['/benefit-request'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc')
      }
    });
    this.benefitRequests = data || [];
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="sahatiApp.benefitRequest.home.title">Benefit Requests</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-benefit-request" [routerLink]="['/benefit-request/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="sahatiApp.benefitRequest.home.createLabel">
            Create a new Benefit Request
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="benefitRequests?.length === 0">
        <span jhiTranslate="sahatiApp.benefitRequest.home.notFound">No benefitRequests found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="benefitRequests?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nameAr"><span jhiTranslate="sahatiApp.benefitRequest.nameAr">Name Ar</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nameEn"><span jhiTranslate="sahatiApp.benefitRequest.nameEn">Name En</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="pointsCost"><span jhiTranslate="sahatiApp.benefitRequest.pointsCost">Points Cost</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="cost"><span jhiTranslate="sahatiApp.benefitRequest.cost">Cost</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="benefitStatus"><span jhiTranslate="sahatiApp.benefitRequest.benefitStatus">Benefit Status</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="notes"><span jhiTranslate="sahatiApp.benefitRequest.notes">Notes</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="categoryNameAr"><span jhiTranslate="sahatiApp.benefitRequest.category">Category</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="hospitalNameAr"><span jhiTranslate="sahatiApp.benefitRequest.hospital">Hospital</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="benefitNameAr"><span jhiTranslate="sahatiApp.benefitRequest.benefit">Benefit</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let benefitRequest of benefitRequests ;trackBy: trackId">
                    <td><a [routerLink]="['/benefit-request', benefitRequest.id, 'view']">{{ benefitRequest.id }}</a></td>
                    <td>{{ benefitRequest.nameAr }}</td>
                    <td>{{ benefitRequest.nameEn }}</td>
                    <td>{{ benefitRequest.pointsCost }}</td>
                    <td>{{ benefitRequest.cost }}</td>
                    <td jhiTranslate="{{ 'sahatiApp.BenefitStatus.' + benefitRequest.benefitStatus }}">{{ benefitRequest.benefitStatus }}</td>
                    <td>{{ benefitRequest.notes }}</td>
                    <td>
                        <div *ngIf="benefitRequest.categoryId">
                            <a [routerLink]="['/category', benefitRequest.categoryId , 'view']" >{{ benefitRequest.categoryNameAr }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="benefitRequest.hospitalId">
                            <a [routerLink]="['/hospital', benefitRequest.hospitalId , 'view']" >{{ benefitRequest.hospitalNameAr }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="benefitRequest.benefitId">
                            <a [routerLink]="['/benefit', benefitRequest.benefitId , 'view']" >{{ benefitRequest.benefitNameAr }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/benefit-request', benefitRequest.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/benefit-request', benefitRequest.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(benefitRequest)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="benefitRequests?.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/benefit-request/benefit-request.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('sahatiApp.benefitRequest.home.title')" id="benefit-request-heading">Benefit Requests</span>
            <router-link :to="{name: 'BenefitRequestCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-benefit-request">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('sahatiApp.benefitRequest.home.createLabel')">
                    Create a new Benefit Request
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && benefitRequests && benefitRequests.length === 0">
            <span v-text="$t('sahatiApp.benefitRequest.home.notFound')">No benefitRequests found</span>
        </div>
        <div class="table-responsive" v-if="benefitRequests && benefitRequests.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('nameAr')"><span v-text="$t('sahatiApp.benefitRequest.nameAr')">Name Ar</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'nameAr'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('nameEn')"><span v-text="$t('sahatiApp.benefitRequest.nameEn')">Name En</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'nameEn'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('pointsCost')"><span v-text="$t('sahatiApp.benefitRequest.pointsCost')">Points Cost</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'pointsCost'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('cost')"><span v-text="$t('sahatiApp.benefitRequest.cost')">Cost</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'cost'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('benefitStatus')"><span v-text="$t('sahatiApp.benefitRequest.benefitStatus')">Benefit Status</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'benefitStatus'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('notes')"><span v-text="$t('sahatiApp.benefitRequest.notes')">Notes</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'notes'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('categoryNameAr')"><span v-text="$t('sahatiApp.benefitRequest.category')">Category</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'categoryNameAr'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('hospitalNameAr')"><span v-text="$t('sahatiApp.benefitRequest.hospital')">Hospital</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'hospitalNameAr'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('benefitNameAr')"><span v-text="$t('sahatiApp.benefitRequest.benefit')">Benefit</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'benefitNameAr'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="benefitRequest in benefitRequests"
                    :key="benefitRequest.id">
                    <td>
                        <router-link :to="{name: 'BenefitRequestView', params: {benefitRequestId: benefitRequest.id}}">{{benefitRequest.id}}</router-link>
                    </td>
                    <td>{{benefitRequest.nameAr}}</td>
                    <td>{{benefitRequest.nameEn}}</td>
                    <td>{{benefitRequest.pointsCost}}</td>
                    <td>{{benefitRequest.cost}}</td>
                    <td v-text="$t('sahatiApp.BenefitStatus.' + benefitRequest.benefitStatus)">{{benefitRequest.benefitStatus}}</td>
                    <td>{{benefitRequest.notes}}</td>
                    <td>
                        <div v-if="benefitRequest.categoryId">
                            <router-link :to="{name: 'CategoryView', params: {categoryId: benefitRequest.categoryId}}">{{benefitRequest.categoryNameAr}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="benefitRequest.hospitalId">
                            <router-link :to="{name: 'HospitalView', params: {hospitalId: benefitRequest.hospitalId}}">{{benefitRequest.hospitalNameAr}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="benefitRequest.benefitId">
                            <router-link :to="{name: 'BenefitView', params: {benefitId: benefitRequest.benefitId}}">{{benefitRequest.benefitNameAr}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'BenefitRequestView', params: {benefitRequestId: benefitRequest.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'BenefitRequestEdit', params: {benefitRequestId: benefitRequest.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(benefitRequest)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="sahatiApp.benefitRequest.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-benefitRequest-heading" v-text="$t('sahatiApp.benefitRequest.delete.question', {'id': removeId})">Are you sure you want to delete this Benefit Request?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-benefitRequest" v-text="$t('entity.action.delete')" v-on:click="removeBenefitRequest()">Delete</button>
            </div>
        </b-modal>
        <div v-show="benefitRequests && benefitRequests.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./benefit-request.component.ts">
</script>
