// src/main/webapp/app/entities/card-transaction/card-transaction.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('sahatiApp.cardTransaction.home.title')" id="card-transaction-heading">Card Transactions</span>
            <router-link :to="{name: 'CardTransactionCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-card-transaction">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('sahatiApp.cardTransaction.home.createLabel')">
                    Create a new Card Transaction
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && cardTransactions && cardTransactions.length === 0">
            <span v-text="$t('sahatiApp.cardTransaction.home.notFound')">No cardTransactions found</span>
        </div>
        <div class="table-responsive" v-if="cardTransactions && cardTransactions.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('transactionNo')"><span v-text="$t('sahatiApp.cardTransaction.transactionNo')">Transaction No</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'transactionNo'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('amount')"><span v-text="$t('sahatiApp.cardTransaction.amount')">Amount</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'amount'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('pointsAmount')"><span v-text="$t('sahatiApp.cardTransaction.pointsAmount')">Points Amount</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'pointsAmount'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('action')"><span v-text="$t('sahatiApp.cardTransaction.action')">Action</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'action'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('notes')"><span v-text="$t('sahatiApp.cardTransaction.notes')">Notes</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'notes'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('cardCardNo')"><span v-text="$t('sahatiApp.cardTransaction.card')">Card</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'cardCardNo'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="cardTransaction in cardTransactions"
                    :key="cardTransaction.id">
                    <td>
                        <router-link :to="{name: 'CardTransactionView', params: {cardTransactionId: cardTransaction.id}}">{{cardTransaction.id}}</router-link>
                    </td>
                    <td>{{cardTransaction.transactionNo}}</td>
                    <td>{{cardTransaction.amount}}</td>
                    <td>{{cardTransaction.pointsAmount}}</td>
                    <td v-text="$t('sahatiApp.TransactionAction.' + cardTransaction.action)">{{cardTransaction.action}}</td>
                    <td>{{cardTransaction.notes}}</td>
                    <td>
                        <div v-if="cardTransaction.cardId">
                            <router-link :to="{name: 'CardView', params: {cardId: cardTransaction.cardId}}">{{cardTransaction.cardCardNo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CardTransactionView', params: {cardTransactionId: cardTransaction.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CardTransactionEdit', params: {cardTransactionId: cardTransaction.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(cardTransaction)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="sahatiApp.cardTransaction.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-cardTransaction-heading" v-text="$t('sahatiApp.cardTransaction.delete.question', {'id': removeId})">Are you sure you want to delete this Card Transaction?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-cardTransaction" v-text="$t('entity.action.delete')" v-on:click="removeCardTransaction()">Delete</button>
            </div>
        </b-modal>
        <div v-show="cardTransactions && cardTransactions.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./card-transaction.component.ts">
</script>

// src/main/webapp/app/entities/card-transaction/card-transaction.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ICardTransaction } from 'app/shared/model/card-transaction.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { CardTransactionService } from './card-transaction.service';
import { CardTransactionDeleteDialogComponent } from './card-transaction-delete-dialog.component';

@Component({
  selector: 'jhi-card-transaction',
  templateUrl: './card-transaction.component.html'
})
export class CardTransactionComponent implements OnInit, OnDestroy {
  cardTransactions?: ICardTransaction[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected cardTransactionService: CardTransactionService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number): void {
    const pageToLoad: number = page || this.page;

    this.cardTransactionService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<ICardTransaction[]>) => this.onSuccess(res.body, res.headers, pageToLoad),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.ascending = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
      this.ngbPaginationPage = data.pagingParams.page;
      this.loadPage();
    });
    this.registerChangeInCardTransactions();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ICardTransaction): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInCardTransactions(): void {
    this.eventSubscriber = this.eventManager.subscribe('cardTransactionListModification', () => this.loadPage());
  }

  delete(cardTransaction: ICardTransaction): void {
    const modalRef = this.modalService.open(CardTransactionDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.cardTransaction = cardTransaction;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: ICardTransaction[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.router.navigate(['/card-transaction'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc')
      }
    });
    this.cardTransactions = data || [];
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="sahatiApp.cardTransaction.home.title">Card Transactions</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-card-transaction" [routerLink]="['/card-transaction/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="sahatiApp.cardTransaction.home.createLabel">
            Create a new Card Transaction
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="cardTransactions?.length === 0">
        <span jhiTranslate="sahatiApp.cardTransaction.home.notFound">No cardTransactions found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="cardTransactions?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="transactionNo"><span jhiTranslate="sahatiApp.cardTransaction.transactionNo">Transaction No</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="amount"><span jhiTranslate="sahatiApp.cardTransaction.amount">Amount</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="pointsAmount"><span jhiTranslate="sahatiApp.cardTransaction.pointsAmount">Points Amount</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="action"><span jhiTranslate="sahatiApp.cardTransaction.action">Action</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="notes"><span jhiTranslate="sahatiApp.cardTransaction.notes">Notes</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="cardCardNo"><span jhiTranslate="sahatiApp.cardTransaction.card">Card</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let cardTransaction of cardTransactions ;trackBy: trackId">
                    <td><a [routerLink]="['/card-transaction', cardTransaction.id, 'view']">{{ cardTransaction.id }}</a></td>
                    <td>{{ cardTransaction.transactionNo }}</td>
                    <td>{{ cardTransaction.amount }}</td>
                    <td>{{ cardTransaction.pointsAmount }}</td>
                    <td jhiTranslate="{{ 'sahatiApp.TransactionAction.' + cardTransaction.action }}">{{ cardTransaction.action }}</td>
                    <td>{{ cardTransaction.notes }}</td>
                    <td>
                        <div *ngIf="cardTransaction.cardId">
                            <a [routerLink]="['/card', cardTransaction.cardId , 'view']" >{{ cardTransaction.cardCardNo }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/card-transaction', cardTransaction.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/card-transaction', cardTransaction.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(cardTransaction)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="cardTransactions?.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
