// src/main/webapp/app/entities/card-transaction/card-transaction-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="sahatiApp.cardTransaction.home.createOrEditLabel" v-text="$t('sahatiApp.cardTransaction.home.createOrEditLabel')">Create or edit a CardTransaction</h2>
                <div>
                    <div class="form-group" v-if="cardTransaction.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="cardTransaction.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.transactionNo')" for="card-transaction-transactionNo">Transaction No</label>
                        <input type="text" class="form-control" name="transactionNo" id="card-transaction-transactionNo"
                            :class="{'valid': !$v.cardTransaction.transactionNo.$invalid, 'invalid': $v.cardTransaction.transactionNo.$invalid }" v-model="$v.cardTransaction.transactionNo.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.amount')" for="card-transaction-amount">Amount</label>
                        <input type="number" class="form-control" name="amount" id="card-transaction-amount"
                            :class="{'valid': !$v.cardTransaction.amount.$invalid, 'invalid': $v.cardTransaction.amount.$invalid }" v-model.number="$v.cardTransaction.amount.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.pointsAmount')" for="card-transaction-pointsAmount">Points Amount</label>
                        <input type="number" class="form-control" name="pointsAmount" id="card-transaction-pointsAmount"
                            :class="{'valid': !$v.cardTransaction.pointsAmount.$invalid, 'invalid': $v.cardTransaction.pointsAmount.$invalid }" v-model.number="$v.cardTransaction.pointsAmount.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.action')" for="card-transaction-action">Action</label>
                        <select class="form-control" name="action" :class="{'valid': !$v.cardTransaction.action.$invalid, 'invalid': $v.cardTransaction.action.$invalid }" v-model="$v.cardTransaction.action.$model" id="card-transaction-action" >
                            <option value="PLUS" v-bind:label="$t('sahatiApp.TransactionAction.PLUS')">PLUS</option>
                            <option value="MINUS" v-bind:label="$t('sahatiApp.TransactionAction.MINUS')">MINUS</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.notes')" for="card-transaction-notes">Notes</label>
                        <input type="text" class="form-control" name="notes" id="card-transaction-notes"
                            :class="{'valid': !$v.cardTransaction.notes.$invalid, 'invalid': $v.cardTransaction.notes.$invalid }" v-model="$v.cardTransaction.notes.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sahatiApp.cardTransaction.card')" for="card-transaction-card">Card</label>
                        <select class="form-control" id="card-transaction-card" name="card" v-model="cardTransaction.cardId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="cardOption.id" v-for="cardOption in cards" :key="cardOption.id">{{cardOption.cardNo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.cardTransaction.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./card-transaction-update.component.ts">
</script>

// src/main/webapp/app/entities/card-transaction/card-transaction-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ICardTransaction, CardTransaction } from 'app/shared/model/card-transaction.model';
import { CardTransactionService } from './card-transaction.service';
import { ICard } from 'app/shared/model/card.model';
import { CardService } from 'app/entities/card/card.service';

@Component({
  selector: 'jhi-card-transaction-update',
  templateUrl: './card-transaction-update.component.html'
})
export class CardTransactionUpdateComponent implements OnInit {
  isSaving = false;
  cards: ICard[] = [];

  editForm = this.fb.group({
    id: [],
    transactionNo: [],
    amount: [],
    pointsAmount: [],
    action: [],
    notes: [],
    cardId: []
  });

  constructor(
    protected cardTransactionService: CardTransactionService,
    protected cardService: CardService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ cardTransaction }) => {
      this.updateForm(cardTransaction);

      this.cardService.query().subscribe((res: HttpResponse<ICard[]>) => (this.cards = res.body || []));
    });
  }

  updateForm(cardTransaction: ICardTransaction): void {
    this.editForm.patchValue({
      id: cardTransaction.id,
      transactionNo: cardTransaction.transactionNo,
      amount: cardTransaction.amount,
      pointsAmount: cardTransaction.pointsAmount,
      action: cardTransaction.action,
      notes: cardTransaction.notes,
      cardId: cardTransaction.cardId
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const cardTransaction = this.createFromForm();
    if (cardTransaction.id !== undefined) {
      this.subscribeToSaveResponse(this.cardTransactionService.update(cardTransaction));
    } else {
      this.subscribeToSaveResponse(this.cardTransactionService.create(cardTransaction));
    }
  }

  private createFromForm(): ICardTransaction {
    return {
      ...new CardTransaction(),
      id: this.editForm.get(['id'])!.value,
      transactionNo: this.editForm.get(['transactionNo'])!.value,
      amount: this.editForm.get(['amount'])!.value,
      pointsAmount: this.editForm.get(['pointsAmount'])!.value,
      action: this.editForm.get(['action'])!.value,
      notes: this.editForm.get(['notes'])!.value,
      cardId: this.editForm.get(['cardId'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICardTransaction>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: ICard): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-card-transaction-heading" jhiTranslate="sahatiApp.cardTransaction.home.createOrEditLabel">Create or edit a Card Transaction</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.transactionNo" for="field_transactionNo">Transaction No</label>
                    <input type="text" class="form-control" name="transactionNo" id="field_transactionNo"
                           formControlName="transactionNo"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.amount" for="field_amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="field_amount"
                           formControlName="amount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.pointsAmount" for="field_pointsAmount">Points Amount</label>
                    <input type="number" class="form-control" name="pointsAmount" id="field_pointsAmount"
                           formControlName="pointsAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.action" for="field_action">Action</label>
                    <select class="form-control" name="action" formControlName="action" id="field_action">
                        <option value="PLUS">{{ 'sahatiApp.TransactionAction.PLUS' | translate }}</option>
                        <option value="MINUS">{{ 'sahatiApp.TransactionAction.MINUS' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.notes" for="field_notes">Notes</label>
                    <input type="text" class="form-control" name="notes" id="field_notes"
                           formControlName="notes"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sahatiApp.cardTransaction.card" for="field_card">Card</label>
                    <select class="form-control" id="field_card" name="card" formControlName="cardId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cardOption.id" *ngFor="let cardOption of cards; trackBy: trackById">{{ cardOption.cardNo }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
